use_frameworks!

platform :ios, '9.0'

target 'ComponentA_Example' do
  pod 'ComponentA', :path => '../'

  target 'ComponentA_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
